### ISSUE TITLE
怎么取消正在执行的命令呢

### ISSUE THREAD

**Issue by DyncKathline** [bookzhan/bzffmpegcmd#2]
目前感觉是同步的

**Comment by bookzhan** [comment]
无法取消，是同步执行的，里面有很多静态变量没法多线程异步执行

**Comment by bookzhan** [comment]
要实现取消功能，你可以自己尝试着修改

**Comment by DyncKathline** [comment]
> 要实现取消功能，你可以自己尝试着修改

ffmpeg 4.0应该不是同步的吧，别的库ffmpeg 4.0可以取消

**Comment by bookzhan** [comment]
要取消需要自己去实现的

**Comment by DyncKathline** [comment]
这里控制就可以了，  https://github.com/xufuji456/FFmpegAndroid/blob/ec4f9ee64129cbc5d5b25aa7f749edf9acd9ae52/app/src/main/cpp/ffmpeg/ffmpeg.c#L4713

**Comment by DyncKathline** [comment]
另外你的进度可以优化 ,参考： https://github.com/yangkun19921001/AVFFmpegLib/blob/9ee523df0bdca8fb8bfda953574a7877335ac131/core/src/main/cpp/fftools_ffmpeg.c#L2028

**Comment by DyncKathline** [comment]
上面是你的代码，下面是修改后的代码，执行速度快了不少  `int executeFFmpegCommand(int64_t handle, const char *command,
                         void (*progressCallBack)(int64_t, int, float)) {
    if (NULL == command) {
        av_log(NULL, AV_LOG_ERROR, "NULL==command");
        return -1;
    }
    av_log(NULL, AV_LOG_DEBUG, "bz_cmd=%s", command);

//    if (!cmdLockHasInit) {
//        pthread_mutex_init(&cmdLock, NULL);//初始化
//        cmdLockHasInit = 1;
//    }
//    pthread_mutex_lock(&cmdLock);

    char *pCommand = (char *) command;
    int stingLen = (int) (strlen(command) + 1);
    char *argv[stingLen];

    char *buffer = NULL;
    int index = 0;
    int isStartYH = 0;
    for (int i = 0; i < stingLen; ++i) {
        char str = *pCommand;
        pCommand++;
        if (NULL == buffer) {
            buffer = malloc(512);
            memset(buffer, 0, 512);
            argv[index++] = buffer;
        }
        //保证引号成对出现
        if (str == '"') {
            if (isStartYH) {
                isStartYH = 0;
            } else {
                isStartYH = 1;
            }
            continue;
        }
        if (str != ' ' || isStartYH) {
            *buffer = str;
            buffer++;
        } else {
            buffer = NULL;
        }
    }
//    for (int i = 0; i < index; ++i) {
//        av_log(NULL, AV_LOG_DEBUG, "cmd=%s", argv[i]);
//    }
    //手动告诉它结束了,防止出现意外
    argv[index] = 0;
    int ret = exe_ffmpeg_cmd(index, argv, handle, progressCallBack);
    for (int i = 0; i < index; ++i) {
        free(argv[i]);
    }
//    pthread_mutex_unlock(&cmdLock);
    return ret;
}`

//这里是我改的
`JNIEXPORT jint JNICALL
Java_com_luoye_bzmedia_FFmpegCMDUtil_executeFFmpegCommand(JNIEnv *env,
                                                          jclass type,
                                                          jobjectArray stringArray,
                                                          jobject actionCallBack) {
    int cmdNum = 0;
    char **argv = NULL;//命令集 二维指针
    jstring *strr = NULL;

    if (stringArray != NULL) {
        cmdNum = (*env)->GetArrayLength(env, stringArray);
        argv = (char **) malloc(sizeof(char *) * cmdNum);
        strr = (jstring *) malloc(sizeof(jstring) * cmdNum);

        int i = 0;
        for (i = 0; i < cmdNum; ++i) {//转换
            strr[i] = (jstring)(*env)->GetObjectArrayElement(env, stringArray, i);
            argv[i] = (char *) (*env)->GetStringUTFChars(env, strr[i], 0);
        }

    }

    int ret = 0;
    if (NULL != actionCallBack) {
        jclass actionClass = (*env)->GetObjectClass(env, actionCallBack);
        jmethodID progressMID = (*env)->GetMethodID(env, actionClass, "progress", "(F)V");
        jmethodID failMID = (*env)->GetMethodID(env, actionClass, "fail", "()V");
        jmethodID successMID = (*env)->GetMethodID(env, actionClass, "success", "()V");


        CallBackInfo onActionListener;
        onActionListener.env = env;
        onActionListener.obj = actionCallBack;
        onActionListener.methodID = progressMID;

        ret = exe_ffmpeg_cmd(cmdNum, argv, (int64_t) (&onActionListener), progressCallBack);
        if (ret < 0) {
            (*env)->CallVoidMethod(env, actionCallBack, failMID);
        } else {
            (*env)->CallVoidMethod(env, actionCallBack, successMID);
        }
        (*env)->DeleteLocalRef(env, actionClass);
    } else {
        ret = exe_ffmpeg_cmd(0, argv, 0, NULL);
    }

    // CLEANUP
    free(strr);
    return ret;
}`

**Comment by bookzhan** [comment]
线程锁不能去掉，不然你会遇到莫名其妙的崩溃

**Comment by bookzhan** [comment]
我加了一个线程锁就是保证同一时间只能有一个线程执行，因为FFmpeg里面用了很多静态变量，没法多线程执行

**Comment by DyncKathline** [comment]
嗯嗯，因为现在只能一个一个命令执行，麻烦你能编译一个4.0的版本吗，我这边测试下取消命令这个操作，因为你的裁剪包是我见过最小的😄

**Comment by bookzhan** [comment]
取消应该和版本没有关系，明天我给你做一下取消功能

**Comment by DyncKathline** [comment]
我觉得有关系，https://github.com/xufuji456/FFmpegAndroid，你可以下载运行下这个程序，他这个可以取消，不是同步的，看了代码都差不多感觉，改动的地方

**Comment by bookzhan** [comment]
我看了他的ffmpeg.c文件里面还是有很多静态变量没有做处理，理论上是不支持多线程调用的，只能支持多进程调用，如果强制多线程调用会出现内存问题

**Comment by bookzhan** [comment]
@DyncKathline 取消命令功能已经添加上去了

**Comment by DyncKathline** [comment]
嗯嗯
