### ISSUE TITLE
FFMpeg 4.4.2 执行命令 失败

### ISSUE THREAD

**Issue by mikelhm** [bookzhan/bzffmpegcmd#5]
调用命令如下：

String cmd = "ffmpeg -i /storage/emulated/0/test/33.mp4 -vn -acodec libmp3lame /storage/emulated/0/test/34_" + System.currentTimeMillis() + ".mp3"

 FFMpegJni.executeFFmpegCommand(cmd)
报错：Error input opening files: Operation no permitted

问题1：是因为输入文件在外部SDCard 自定义目录，没有权限么？ 
但是我的APP 已经申请了「所有文件管理权限」以及「读写权限」，也还是一样。 
另外，如果「输入文件目录是Download 目录」则没有问题。

问题2: 在没采用 「JNI 调用方案」之前，我用的是「可执行 FFmpeg so」 执行命令 即 "libffmpeg.so -i /storage/emulated/0/test/33.mp4 -vn -acodec libmp3lame /storage/emulated/0/test/34_" + System.currentTimeMillis() + ".mp3"  这种方式不会报错。 
但是这种方式 在 target sdk 升级 29 后不能使用 「动态加载的可执行So」来执行 FFMpeg 命令，只能使用 「内置的可执行SO」来执行FFMpeg 命令 ，所以需要用上面的JNI 调用方案。

 为什么「内置的可执行So 」输入文件是外部SDCard目录没有问题， 「JNI 调用方案」输入文件是外部SDCard目录却报错？

使用该工程 APP demo 应该能复现，设备 Android 14 (11+)

**Comment by mikelhm** [comment]
这个用ffmpeg 6.0 验证没有问题

**Comment by bookzhan** [comment]
OK，是权限请求的问题，mater分支适配了Android新的权限请求
